version: '3'
services:
  app:
    container_name: memberships
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - XDEBUG_MODE=coverage
    restart: always
    volumes:
      - ./:/var/www
